### ISSUE TITLE
Sort line graph labels based on team id, not lexigraphically

### ISSUE THREAD

**Issue by pwnbus** [scoringengine/scoringengine#121]
If we have over 10 teams, we sort the teams based on a string comparison, so that our ordering of teams goes:

team1
team10
team11
team12
team2
team3

We need to update this so that it goes team1, team2, team3....team10, team11, team12

**Comment by RustyBower** [comment]
There appears to be a bug with chartjs, we are passing in our dictionary sorted (1-10), but it insists on sorting it 1,10, 2-9

**Comment by RustyBower** [comment]
Going to investigate highcharts and see if that fixes things?
