### ISSUE TITLE
Implement IPv4 checks from cyberengine

### ISSUE THREAD

**Issue by zmallen** [scoringengine/scoringengine#130]
https://github.com/RITSPARSA/cyberengine/tree/master/checks/ipv4

- ~~dns~~
- ~~ftp~~
- ftps
- http
- https
- ~~icmp~~
- mysql
- nfs
- pop3
- pop3s
- smb
- smtp
- smtps
- ssh

**Comment by zmallen** [comment]
#129 -> FTP done

**Comment by pwnbus** [comment]
Closing since we've added the remaining ones in https://github.com/pwnbus/scoring_engine/pull/223
