### ISSUE TITLE
Determine build & versions for command line tools in checks for environment

### ISSUE THREAD

**Issue by zmallen** [scoringengine/scoringengine#131]
We need a standardized version list for the command line tools used in the Checks modules. I can then take these and write a cookbook/ansible file to get a standardized deployment of the scoring engine

**Comment by pwnbus** [comment]
Instead of using curl in most of the checks, I've decided to go with medusa. Closing this issue since I don't think it's an issue anymore (I added a generic login check with FTP as well).
