### ISSUE TITLE
App Logging, Monitoring & Alerting

### ISSUE THREAD

**Issue by zmallen** [scoringengine/scoringengine#133]
The app should replace all `print` statements with something to syslog, and we should have a plan in place to monitor for specific app failures (Checks failing to load, database connection resets) to allow the scoring team to configure alerts and response to faults in the system

**Comment by pwnbus** [comment]
Would be nice to have a config option of the verbosity of logs as well

**Comment by pwnbus** [comment]
Replaced all print statements with a logger, and the systemd scripts send it to syslog. I also created a couple configs for rsyslog to drop each (web, worker, engine) into separate log files.
