### ISSUE TITLE
Shuffle results from /api/overview/data json output

### ISSUE THREAD

**Issue by pwnbus** [scoringengine/scoringengine#155]
To help in randomizing teams when people parse the scripts, we should shuffle the team ordering in "/api/overview/data". This returns json.

**Comment by pwnbus** [comment]
I looked into this, and it turns out that the jsonify method automagically sorts the inputted dict for us. We can turn this off in the application configuration spot, however, we would setting it globally for the entire app.

**Comment by RustyBower** [comment]
I converted this from jsonify to json.dumps, and it's kind of randomizes. Unfortunately I think we need to actually randomize the keys and put in an orderedDict or something

**Comment by pwnbus** [comment]
Implemented in https://github.com/pwnbus/scoring_engine/pull/231
