### ISSUE TITLE
Implement way to populate the sponsorship image information

### ISSUE THREAD

**Issue by pwnbus** [scoringengine/scoringengine#159]
It would be cool if we could define this in the config file in some sort of data structure, maybe something as simple as a dict:

`{`
`    "RIT": "images/sponsorships/rit.jpg",`
`    "SPARSA": "images/sponsorships/sparsa.jpg"`
`}`

The welcoming page in the web ui would be auto populated from this config variable.

**Comment by RustyBower** [comment]
`"RIT": {`
`"level": "Diamond",`
`"image": "image.jpg"`
`}`

**Comment by pwnbus** [comment]
Completed in https://github.com/pwnbus/scoring_engine/commit/5e454494a359b9121663e6f82f69679f43a7205a#diff-0b7cb98f370b15c888a0deedb15673ad

This is added in the engine.conf file.
