### ISSUE TITLE
Scoring overview as a single page

### ISSUE THREAD

**Issue by kengraf** [scoringengine/scoringengine#346]
Scrolling is required when 8 to 10+ services are in play.

Rather than showing the full URL involved maybe just a yes/no/maybe checkmark?

**Comment by pwnbus** [comment]
That's an interesting idea, @kengraf  . We were originally thinking it would be nice to have the IP info for folks on red team for example, but maybe we can accomplish the same by having a yes/no checkmark, with a hover-over that displays the hostname:port.

**Comment by kengraf** [comment]
I like it.


________________________________
Ken Graf - Computer Security Lecturer
Email: ken.graf@cs.unh.edu
Office: Kingsbury N211
Phone: 603-782-1723
________________________________

**Comment by pwnbus** [comment]
Closing issue since this feature has been merged!
