### ISSUE TITLE
Add RDP check

### ISSUE THREAD

**Issue by pwnbus** [scoringengine/scoringengine#397]
We should add an RDP check. I believe impacket will be useful here.

**Comment by mubix** [comment]
Use impacket library example `rdp-check.py`

**Comment by RustyBower** [comment]
This one might be hard to do in docker... https://social.msdn.microsoft.com/Forums/en-US/f4314bc8-52d0-477c-9ecc-86a578b53814/no-support-expected-for-rdp-in-containers-for-windows-server-2016?forum=windowscontainers#f4314bc8-52d0-477c-9ecc-86a578b53814

**Comment by pwnbus** [comment]
Unfortunately impacket is python2.7, which might be a pain in the ass to have setup alongside python3. We might be able to use xfreerdp, which can be installed via `apt-get install freerdp-x11` and checked via `xfreerdp --ignore-certificate --authonly -u ttesterson -p testtests <ip>`. It only prints if the creds are wrong, but we might be able to echo something if the exit code is 0.

**Comment by pwnbus** [comment]
Incomplete implementation in https://github.com/pwnbus/scoring_engine/pull/449/files

**Comment by pwnbus** [comment]
Decided to implement in https://github.com/scoringengine/scoringengine/pull/483 in favor.

**Comment by pwnbus** [comment]
Closing since this issue is resolved! We were unable to get the docker container working, but have created a separate issue for that (https://github.com/scoringengine/scoringengine/issues/484)
