### ISSUE TITLE
Agent to deploy to blue team boxes to score

### ISSUE THREAD

**Issue by RustyBower** [scoringengine/scoringengine#402]

**Comment by mubix** [comment]
# Red Team Scoring Binary

### Description:
We are looking to make it possible to have Red Team scoring happen in some way. The thought is that when a shell is gained, and maintained a point loss should occur.

### Requirements:

- Builder
  - Creates the binaries on the scoreboard and provides download links to the Red Team
  - Automatically builds for the IP addresses the scoreboard has 'access' to
- Actions
  - The binary detects what level of access it's running under. On Windows it should just detect "IsUserAdmin" and on Linux checking it's access to `cat /etc/ssh/ssh_host_dsa_key` maybe? not sure.of a certain way to say I'm basically root. (like if another user is created that has kernel permissions or whatever)
  - The binary then checks in from the Team's network. It checks in twice as fast as whatever the check in time is specified in the scoreboard. This is to facilitate how it's actually scored
  - Scoring side the worker just checks some log on the scoreboard and determines if the host has pinged in or not and at what level. 
- Scoreboard
  - It would be nice to have some sort of indication of Red Team "intrusions" even if it's just a number like "Your team has 10 root intrusions and 3 user based intrusions" or even as simple as just having a Red 10/7 under their team name.

- Have each check in be verified cryptographically either with the binary checking in, or the worker side. But the binaries should be hard to spoof both from a Red Team perspective

### Binaries

- Windows Service Binary
- Windows Binary (EXE and DLL)
- Linux (32 and 64 bit) staticly linked binary

# Internet Proof Service Binary

### Description:
Do to the lack of Internet access at MACCDC, it would be nice to have a simpler service binary or installer that would talk to the Scoreboard on it's accessible IPs and "prove" that it had access to the "Internet". The only requirement is that the binary can be installed somehow on Windows and Linux machines in a persistent way and makes it very difficult to spoof.

This should operate much like the Red Team binary.

**Comment by s-newman** [comment]
Another way of providing this functionality could be adding some sort of API endpoint that could be used to record beacons per team and per host, similar to how pwnboard works. The endpoint could also accept metadata with each callback, so attributes like permission level can be used to provide more detailed scoring feedback.

This way, enterprising blue teamers couldn't search specifically for "the scoring engine red team binary" (if it was made public) on their boxes, since regular ol' red team implants would be sending back the scoring information.

**Comment by RustyBower** [comment]
Yeah I've been noodling on how to do this in a deterministic way. Gonna try to get something build out in the next few weeks.

**Comment by RustyBower** [comment]
I believe this is covered by the work @wumb0 did
