### ISSUE TITLE
Add white team button to manually expire cache

### ISSUE THREAD

**Issue by RustyBower** [scoringengine/scoringengine#411]
There is a slight edge case where an unauthorized route can be cached for a team. Add manual cache expiration for white team, so they can expire the cache any team or the whole competition

**Comment by pwnbus** [comment]
I think we can close this issue since it's no longer needed, thoughts?

**Comment by RustyBower** [comment]
I believe you are correct since we redid some of the caching stuff. I'll keep an eye out and reopen this if necessary.
