### ISSUE TITLE
Scoring engine slow down with large number of down services

### ISSUE THREAD

**Issue by jplsek** [scoringengine/scoringengine#503]
Last year at the NECCDC at UNH, there was a problem where when more services went down, the scoring engine kept getting slower (rounds would take longer to complete).

Have you had a chance to look into this? It could have also been a configuration issue, but I'm not sure how the scoring engine was set up.

(I only found out about `celery` today, so my assumptions below may be incorrect.)

In case it wasn't, it is possible that it got slower because as more services timed out, the queue of tasks would become larger, instead of the tasks running concurrently.

Since `celery`'s default concurrency option is to run as many tasks as cores available, would adding `--concurrency=X`, where X _could_ be total number of possible service tests per worker, possibly improve this? Since testing each service is relatively unintensive, especially when the services are timing out, having more threads running tests than cores should help mitigate the queues. 

https://github.com/scoringengine/scoringengine/blob/0a834317ff4294c212feaa89a2c5708eb38fcd7a/bin/worker#L14

**Comment by RustyBower** [comment]
Hey Jeremy,

We've made a ton of improvements since last year in terms of performance, both on the frontend and the backend. 

On the backend, we've added a hard timeout for all service checks, which will prevent the issue you were seeing with elongated rounds (something we also saw last year at a few other events as well). Adding more celery workers is definitely something you can do if you want, but it shouldn't be necessary with the timeouts that we've added.

@pwnbus any other thoughts?

Rusty

**Comment by pwnbus** [comment]
Each check has 30 seconds to timeout, so if more are hitting that timeout, then the round time will take longer. I'm wondering if 30 seconds is too much, or if we can reduce that to say, 15 seconds?

In addition, I think we can have the concurrency param be controlled by an environment variable, so we can default to # of cores, but allow it to be modified.

If you use the docker environment, we can also add a value to the docker-compose to run a customizable amount of worker containers as well (which call celery)

**Comment by jplsek** [comment]
That's good to hear about the improvements.
I think the environment variable is a good idea.
We might try to set up the scoring engine in our lab again to see how the difference is like with these improvements. Maybe we'll also try adding the concurrent parameter ourselves to see if that makes any noticeable difference.
Thanks for the awesome work on the scoring engine!

**Comment by pwnbus** [comment]
Sounds good, thanks for your feedback!

Let me know if you run into any problems or have any other feedback!

**Comment by dookgit** [comment]
Hey all.  Currently using ScoringEngine in a CTF (Amazing job)

I'm experiencing the slowdown when some services are fully off.  I have it monitoring some servers, which are currently offline, and i'll turn em off later on in the game.

But the round time is at like...10-12mins atm.  Where i can modify the check timeouts?
I'm running the docker version btw

**Comment by RustyBower** [comment]
hey @dookgit, if when defining your checks, you can specify a timeout ala https://github.com/scoringengine/scoringengine/blob/b623e7ee0bb57b50160dcbe44e6e9f66932d852b/bin/competition.yaml#L398

If that doesn't work, go ahead and open a new issue.

**Comment by dookgit** [comment]
Got it.  Cheers!

**Comment by dookgit** [comment]
That worked perfectly, sped things up a lot.  I also chopped the "Round Sleep Time" down from 180secs to 5secs, as...i'm just using this to monitor services.

Thanks folks
