### ISSUE TITLE
Cache blue page service view

### ISSUE THREAD

**Issue by pwnbus** [scoringengine/scoringengine#624]
When there's a bunch of data, the blue team service page takes a while to load, making it difficult to troubleshoot and modify port/host.

**Comment by RustyBower** [comment]
It looks like we already cache this on https://github.com/scoringengine/scoringengine/blob/master/scoring_engine/web/views/api/team.py#L32

**Comment by RustyBower** [comment]
I believe this is already cached, the query is expensive to hit it, so that might be causing the performance issues we were seeing.
