### ISSUE TITLE
OPTIONS issue in config_load.py

### ISSUE THREAD

**Issue by Kevin-Magee** [scoringengine/scoringengine#659]
![OPTIONS](https://user-images.githubusercontent.com/50968032/66597803-4c8c5400-eb65-11e9-8afa-f4d37f177492.PNG)

**Comment by RustyBower** [comment]
It looks like the engine.conf that you are using doesn't have an OPTIONS category. See https://github.com/scoringengine/scoringengine/blob/master/engine.conf.inc for an example of how this engine.conf should look.

**Comment by Kevin-Magee** [comment]
I looked at the engine.conf.inc file and the one that I am running is the same as the one in the documentation. I followed the documentation from the manual installation part and it always breaks at the pip install line.

**Comment by Kevin-Magee** [comment]
I think i might have found the issue do i have to rename the engine.conf.inc to engine.conf?

**Comment by RustyBower** [comment]
Yes! If you are looking to leverage docker, https://github.com/scoringengine/scoringengine/blob/master/docker/base/Dockerfile#L19, you can see where it's copied in there.

If you are going bare metal, you can see that we copy over the engine.conf per the docs https://scoringengine.readthedocs.io/en/latest/installation/base.html#copy-modify-configuration

**Comment by Kevin-Magee** [comment]
Okay this is another error I was getting from the engine, web, and worker log. Can you point me in any directions?
![Module](https://user-images.githubusercontent.com/50968032/66604862-93ce1100-eb74-11e9-8e77-1e9b2a3f22d8.PNG)

**Comment by RustyBower** [comment]
Did you follow the instructions here https://scoringengine.readthedocs.io/en/latest/installation/base.html#install-scoring-engine-src-python-dependencies? It sounds like you haven't installed the scoring engine dependency

**Comment by Kevin-Magee** [comment]
Yes i followed those steps and it said all were installed successfully

**Comment by RustyBower** [comment]
Can you drop into your venv and run pip freeze to make sure it's seeing it?

**Comment by Kevin-Magee** [comment]
Is that what it should output?
![PIPFRZ](https://user-images.githubusercontent.com/50968032/66609775-85d1bd80-eb7f-11e9-9320-3c1361dbc496.PNG)

**Comment by Kevin-Magee** [comment]
Now im just getting that error on the the engine and worker.

**Comment by RustyBower** [comment]
So the scoring_engine package hasn't been installed in the venv.

While you're in your venv, run pip install -e /home/engine/scoring_engine/src/ and make sure the package shows up in pip freeze

**Comment by Kevin-Magee** [comment]
Okay got that all working and service is trying to show up online. But all pages are giving an internal server error (overload or applications fault). I'm assuming that it is because the engine.conf is miss configured.
![ENGINE](https://user-images.githubusercontent.com/50968032/66617684-c2abad80-eb9b-11e9-9e68-5a6c127273b5.PNG)

**Comment by RustyBower** [comment]
Set debug = True and it should give you the error

**Comment by Kevin-Magee** [comment]
it came back with a 502 bad gateway and in the logs it said unknown mysql server host

**Comment by RustyBower** [comment]
You have to configure one. Right now you have user:password@host.

**Comment by Kevin-Magee** [comment]
okay so it would be the user a create as a mysql user? so l like mysqluser:1234@localhost?

**Comment by RustyBower** [comment]
Correct. If the server is running on localhost.
