### ISSUE TITLE
Start a new competition?

### ISSUE THREAD

**Issue by SdogfromJtown92** [scoringengine/scoringengine#661]
I was looking through your documentation and was wondering if there is any documentation about how to reset the competition environment and edit the services that are being scored?

**Comment by pwnbus** [comment]
The competition data is stored in https://github.com/scoringengine/scoringengine/blob/master/bin/competition.yaml which is where all of each team's services are configured as well. To "reset" a competition, you would run this:
```
su engine
vi /home/engine/scoring_engine/src/bin/competition.yaml
source /home/engine/scoring_engine/env/bin/activate
/home/engine/scoring_engine/src/bin/setup --overwrite-db
```

Basically the same exact commands as https://scoringengine.readthedocs.io/en/latest/installation/engine.html#setup-scoring-engine-teams-and-services but we'd instead, set the `--overwrite-db` flag when running the setup script.

**Comment by SdogfromJtown92** [comment]
I ran that and it gave back a 2013 mysql error. I ran it in sudo and it said no module named scoring_engine.models.service. Pip freeze says scoring_engine is installed.
Deleted show tables but returns error on some.

**Comment by RustyBower** [comment]
What was the mysql error you got?

**Comment by SdogfromJtown92** [comment]
2013, 'Lost connection to MySQL server during query', on DROP TABLE checks.

**Comment by RustyBower** [comment]
Did you set all the values for the server in the configuration file?

**Comment by SdogfromJtown92** [comment]
In the engine.conf??? and i cant drop the table going into mysql and doing it manually

**Comment by RustyBower** [comment]
Yeah in engine.conf.

If you’re in docker you’ll need to mount that file and specify the proper
location.

If you’re running bare metal. You’ll need to edit that file.

Instructions for both ways should be in the docs.
