### ISSUE TITLE
ImportError: cannot import name 'url_encode'

### ISSUE THREAD

**Issue by joe-graham** [scoringengine/scoringengine#670]
Werkzeug changed the url_encode function from werkzeug.url_encode to werkzeug.urls.url_encode. Current setup results in this error on startup of the web container: 
![image](https://user-images.githubusercontent.com/11893346/74106339-086d8800-4b34-11ea-93aa-171f33c9875c.png)

Simple fix should be to bump flask-wtf to version 0.14.3 as referenced [here](https://github.com/lepture/flask-wtf/commit/8b028994b68f5fffbf920770a0b4943a5225b282).

**Comment by Kaoloth** [comment]
You posted this while I was writing up my own report. See my issue [here](https://github.com/scoringengine/scoringengine/issues/672). I was able to get around it by specifying the version of werkzeug in the setup.py to 0.16.0.

**Comment by joe-graham** [comment]
Also getting this error after build, bumping Flask-Caching to 1.8.0 fixes it:
![image](https://user-images.githubusercontent.com/11893346/74106639-85016600-4b36-11ea-9c21-797e1466849b.png)

**Comment by RustyBower** [comment]
Yah this is fixed with pinning Werkzeug to <1.0, which removed the contrib module

**Comment by skrsfix** [comment]
Thanks for filing & referencing this issue. My airflow setup failed with a similar issue today.

I was able to fix it up with this pin `Werkzeug==0.16.1`

**Comment by nic-github-ad** [comment]
Thanks everyone. 

My issue fixed by updating Werkzeug=0.16.1

**Comment by wumb0** [comment]
thanks guys, this just fixed the issue i was having with one of my sites after upgrading some stuff.
