### ISSUE TITLE
Feature Request/How To Do Stuff

### ISSUE THREAD

**Issue by dookgit** [scoringengine/scoringengine#673]
First up, great job folks.  I follow the Manual guide to get ScoringEngine up and running on Ubuntu 16.04, and it's running great.
I love the modular checks, makes life uber easy.

I had a couple of possible feature requests, or maybe just understand how to do things properly.

1 - Anyway there can be a Start/Stop switch in the Competition section, so you can start everything up etc, and then start the game when ready.   (A "test" option, might be good to, so you can quickly test that all monitored services are contactable and responding as expected too, before fully starting the game)

2 - Is there an easy way to add new hosts to be checked in the GUI, rather than modifying the competition.yaml file during setup?  Be good if you could add additional hosts to be scored during a game.

3 - I noticed theres thje "Red Team" on the scoreboard, what this for?  Obviously for the dedicated Red Team playing the game, but...what can they do on the scoreboard?  Submit stuff etc?

Thanks again, i'm uber keen to be hopefully using this scoreboard in a BlueVBlue CTF in Australia in March, as it does exactly what i need.

**Comment by RustyBower** [comment]
Hey @dookgit,

Thanks for checking out the project!

1) Adding start/stop functionality has been on the back of our minds for a bit now, and this might be a good time to implement it.

2) Similar to 1, we've built most of the functionality to be in the CLI/competition.yml, but extending this functionality to the GUI shouldn't be too difficult.

3) Correct, this is for red team to "prove" ownership/access to boxes, but this should be pulled from master and put onto a separate module to install.

Rusty

**Comment by dookgit** [comment]
Thanks for getting back to me mate

Be great if that functionality can make it in, i'm not a dev in anyway, so can't help, but i have a buddy who might be able to help with the code if you need some extra hands.

So for the Red Team "proving of owning another box" is this a module that exists, or on the todo list.
Not sure if you've ever seen the ProsVJoes CTF in BSidesLV, but they do that using a "beacon" system, where the red team, or an opposing blue team echo back a unique string from an opposing teams server.

Once the scoreboard receives that, it can match the unique string to the attacking team (or red team) and know which box the string has come from (i think via source IP)  then can display it on the scoreboard.


Anyways, thanks again for getting back to me, i appreciate the work thats gone into the scoreboard so far, it'a awesome

**Comment by RustyBower** [comment]
Hey dookgit

Unfortunately I haven't had a chance to get some of those features into the UI, it's slightly more complicated since it's Python talking directly to the system to stop services.

As for the red team stuff, I am actually gonna pull that into a separate Python module that folks can install, rather than have it be a part of the base system (this will also allow us to have other "plugin" style features like CTFs, etc.)

If you do need a hand getting things up and running, just let me know and I'm happy to walk you through it

**Comment by dookgit** [comment]
Hey Rusty, thanks for the reply.

I've actually managed to get it up and running, and the monitoring is working beautifully.  Well done to you and all your crew.
I'll be using it for a "backup monitor" on a Red V Blue CTF i'm running in 2 weeks time.  Still using the main PvJ Scorebot for the game, as it has those "beacons", but yours for a way to see if teams have altered the services in anyway.

After i've finished this CTF i'll try and do some "how to guides" and push to the repo, and..people can correct me where i've got it wrong :)

But yeah, it's working great atm.

**Comment by RustyBower** [comment]
Awesome to hear! If there's any gaps or features that you would be
interested, just drop in a github issue and we can throw it on the backlog

Rusty

**Comment by RustyBower** [comment]
Closing this out for now, but if you think of any features, drop an issue!
