### ISSUE TITLE
Get admin/stats page pulling in redis stats

### ISSUE THREAD

**Issue by RustyBower** [scoringengine/scoringengine#87]

**Comment by pwnbus** [comment]
In terms of # of items in the worker queue, and finished queue, you can use these classes:

https://github.com/pwnbus/scoring_engine/blob/master/scoring_engine/engine/finished_queue.py
https://github.com/pwnbus/scoring_engine/blob/master/scoring_engine/engine/worker_queue.py

For example:
`worker_queue = WorkerQueue()`
`worker_queue.size()`

**Comment by pwnbus** [comment]
Implemented in https://github.com/pwnbus/scoring_engine/pull/153
